package tech.icc.filesrv.common.vo.task;

import lombok.Builder;
import tech.icc.filesrv.common.vo.file.FileRelations;

/**
 * Derived file - e.g., thumbnail, transcoded file.
 * <p>
 * Represents a file generated during callback processing. Each derived file
 * has its own unique identifier (fKey) and can track relationships to its
 * source file and other related files.
 * </p>
 *
 * @param type        derived file type, e.g., "THUMBNAIL", "PREVIEW", "TRANSCODE"
 * @param fKey        unique file key (identifier generated by File domain)
 * @param fileId      file identifier (deprecated, use fKey instead)
 * @param path        storage path of the derived file
 * @param contentType MIME type of the derived file
 * @param size        size of the derived file in bytes
 * @param relations   file relationships (source, current main, and derived files)
 */
@Builder
public record DerivedFile(
        String type,
        String fKey,
        String fileId,
        String path,
        String contentType,
        Long size,
        FileRelations relations
) {
    /**
     * Create a derived file with minimal information (no relations).
     *
     * @param type        the derived file type
     * @param fKey        the unique file key
     * @param path        the storage path
     * @param contentType the MIME type
     * @param size        the file size
     * @return a DerivedFile instance with empty relations
     */
    public static DerivedFile of(String type, String fKey, String path, 
                                 String contentType, Long size) {
        return new DerivedFile(type, fKey, fKey, path, contentType, size, 
                              FileRelations.empty());
    }
}
